export const ROOT_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const WELCOME_ROUTE = '/welcome'
export const NOTIFICATIONFORM_ROUTE = '/notification'
export const PROFILE_ROUTE = '/profile'
export const FEEDBACKFORM_ROUTE = '/feedback'
